# Generated by Django 2.2.3 on 2019-07-08 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190706_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='alert_time',
            field=models.TimeField(default='05:00 PM'),
        ),
    ]
