# Generated by Django 2.2.3 on 2019-07-11 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190707_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='interval',
            field=models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly')], default='Daily', max_length=6),
        ),
    ]
