# Generated by Django 2.2.3 on 2019-08-03 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190710_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='interval',
            field=models.IntegerField(choices=[(24, 24), (12, 12), (8, 8)], default=24),
        ),
    ]
