# Generated by Django 2.2.3 on 2019-08-03 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20190803_1030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='search_length',
        ),
    ]
