# Generated by Django 2.2.3 on 2019-08-18 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_alert_search_length'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Alert',
        ),
    ]
