# Generated by Django 2.2.3 on 2019-08-03 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherstation',
            name='timezone',
            field=models.CharField(default='America/New York', max_length=50),
        ),
    ]
