# Generated by Django 2.2.3 on 2019-08-03 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_weatherstation_timezone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_code', models.CharField(max_length=5, null=True, unique=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_daytime', models.BooleanField(default=True)),
                ('temperature', models.IntegerField()),
                ('temperature_unit', models.CharField(default='F', max_length=5)),
                ('wind_speed', models.CharField(default='0 mph', max_length=10)),
                ('wind_direction', models.CharField(default='N', max_length=10)),
                ('short_forecast', models.TextField()),
                ('detailed_forecast', models.TextField()),
            ],
        ),
    ]
