# Generated by Django 2.2.3 on 2019-08-04 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_weather'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='zip_code',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
